# Generated by Django 5.2.6 on 2025-09-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitem_size_product_brand_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cartitem/'),
        ),
    ]
